/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      height: {
        header: "80px",
        post_img: "328px",
        successImg: "53px",
        imgUpload: "180px",
        imgUploaded: "56px",
        textarea: "124px",
      },
      width: {
        successImg: "53px",
        40: "40px",
        post: "408px",
      },
      maxWidth: {
        post: "408px",
        popup: "480px",
        blog: "600px",
        authorInp: "calc(50% - 12px)",
        whole_post: "720px",
      },
      colors: {
        white: "#fff",
        black_: "#1A1A1F",
        gray_: "#85858D",
        dark_gray: "#404049",
        header_login: "#5D37F3",
        see_more: "#5D37F3",
        err: "#EA1919",
        err_bg: "#FAF2F3",
        success: "#14D81C",
        success_bg: "#F8FFF8",
        active_inp: "#5D37F3",
        active_inp_bg: "#F7F7FF",
        imgUpload: "#F4F3FF",
        imgUploaded: "#F2F2FA",
        inp_bg: "#FCFCFD",
        disabled_btn: "#E4E3EB",
      },
      padding: {
        main: "76px",
        content_y: "66px",
        header_login_x: "20px",
        header_login_y: "10px",
        component_item_x: "16px",
        component_item_y: "8px",
        popup_x: "20px",
        popup_y: "40px",
        inp_x: "16px",
        inp_y: "12px",
        small_component_x: "10px",
        small_component_y: "6px",
      },
      margin: {
        home_container_t: "64px",
        newBlogCont: "40px",
        whole_post_t: "40px",
        whole_post_b: "100px",
      },
      zIndex: {
        header: 99,
        popup: 999,
      },
      fontSize: {
        normal: "14px",
        64: "64px",
        16: "16px",
        12: "12px",
        20: "20px",
        24: "24px",
        32: "32px",
      },
      fontWeight: {
        700: 700,
        500: 500,
        400: 400,
      },
      lineHeight: {
        72: "72px",
        post_desc: "28px",
        32: "32px",
        20: "20px",
        40: "40px",
      },
      gap: {
        components: "24px",
        post_info: "16px",
        post: "24px",
        post_container_x: "32px",
        post_container_y: "56px",
        err: "8px",
        blog: "40px",
        addBlog: "24px",
        whole_post_info: "24px",
      },
      borderColor: {
        input_normal: "#E4E3EB",
        imgUpload: "#85858D",
      },
      borderWidth: {
        input: "1px",
      },
      borderRadius: {
        header_login: "8px",
        component_item: "30px",
        12: "12px",
      },
      spacing: {
        x_icon: "20px",
        back_icon_t: "120px",
        back_icon_l: "4rem",
      },
    },
  },
  plugins: [],
};
